### ISSUE TITLE
Layout broken

### ISSUE THREAD

**Issue by nwatab** [asterisk37n/bookmeter_lib_chrome#18]
sometimes table layout broken. I propose li element, not table.

**Comment by nwatab** [comment]
![4](https://cloud.githubusercontent.com/assets/16299750/21209975/0bd6dc44-c2bb-11e6-80d6-792a3cf22336.png)

**Comment by s-onuma** [comment]
How can I reproduce it? I need more information.

**Comment by nwatab** [comment]
I do not know how it happened. nowrap in CSS will work. I do it.
