### ISSUE TITLE
NOT STORED in <CITY>

### ISSUE THREAD

**Issue by nwatab** [asterisk37n/bookmeter_lib_chrome#37]
change message when a book is not stored in libraries,
before: NOT STORED
after: NOT STORED IN <city>
for example, NOT STORED IN 東京都中央区

**Comment by nwatab** [comment]
also we have to change "Loading... " into "Loading from <city>".

**Comment by s-onuma** [comment]
Why was this closed?

**Comment by nwatab** [comment]
it's my mistake. it's should not be closed
